org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod
mod_id=fscrates
mod_name=Fantastic Crates
mod_license=Todos los derechos reservados - (c) Pewez. Prohibida la copia, descompilaci\u00f3n, redistribuci\u00f3n o uso del c\u00f3digo sin autorizaci\u00f3n expresa del autor.
mod_version=3.0.0
mod_group_id=com.fscrates
mod_authors=Pewez
mod_description=El sistema de crates m\u00e1s avanzado para Forge 1.20.1: crates y llaves con rarezas, GUI editable en juego, recompensas con NBT completo, cooldown por jugador y un motor de animaciones modular e ilimitado.
